name: machine-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - python=3.11.9
  - pip:
      - libsvm-official==3.32.0
      - matplotlib==3.9.0
      - numpy==1.26.4
      - scipy==1.13.0
      - sentencepiece==0.2.0
      - torch==2.3.1+cu118
      - torchaudio==2.3.1+cu118
      - torchvision==0.18.1+cu118
      - tqdm==4.66.4
      - transformers==4.42.3
